/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as ChildrenRouteImport } from './routes/children'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as MainBookRouteImport } from './routes/main-book'
import { Route as ReportRouteImport } from './routes/report'
import { Route as TimecardRouteImport } from './routes/timecard'
import { Route as ApiAssocListRouteImport } from './routes/api/assoc-list'
import { Route as ApiAssocManageRouteImport } from './routes/api/assoc-manage'
import { Route as ChildrenIndexRouteImport } from './routes/children.index'
import { Route as ChildrenChildIdRouteImport } from './routes/children.$childId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenRoute = ChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const MainBookRoute = MainBookRouteImport.update({
  id: '/main-book',
  path: '/main-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const TimecardRoute = TimecardRouteImport.update({
  id: '/timecard',
  path: '/timecard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssocListRoute = ApiAssocListRouteImport.update({
  id: '/api/assoc-list',
  path: '/api/assoc-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssocManageRoute = ApiAssocManageRouteImport.update({
  id: '/api/assoc-manage',
  path: '/api/assoc-manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenIndexRoute = ChildrenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChildrenRoute,
} as any)
const ChildrenChildIdRoute = ChildrenChildIdRouteImport.update({
  id: '/$childId',
  path: '/$childId',
  getParentRoute: () => ChildrenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/children': typeof ChildrenRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/main-book': typeof MainBookRoute
  '/report': typeof ReportRoute
  '/timecard': typeof TimecardRoute
  '/api/assoc-list': typeof ApiAssocListRoute
  '/api/assoc-manage': typeof ApiAssocManageRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/children/': typeof ChildrenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/main-book': typeof MainBookRoute
  '/report': typeof ReportRoute
  '/timecard': typeof TimecardRoute
  '/api/assoc-list': typeof ApiAssocListRoute
  '/api/assoc-manage': typeof ApiAssocManageRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/children': typeof ChildrenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/children': typeof ChildrenRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/diagnose': typeof DiagnoseRoute
  '/main-book': typeof MainBookRoute
  '/report': typeof ReportRoute
  '/timecard': typeof TimecardRoute
  '/api/assoc-list': typeof ApiAssocListRoute
  '/api/assoc-manage': typeof ApiAssocManageRoute
  '/children/$childId': typeof ChildrenChildIdRoute
  '/children/': typeof ChildrenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/children'
    | '/dashboard'
    | '/diagnose'
    | '/main-book'
    | '/report'
    | '/timecard'
    | '/api/assoc-list'
    | '/api/assoc-manage'
    | '/children/$childId'
    | '/children/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/dashboard'
    | '/diagnose'
    | '/main-book'
    | '/report'
    | '/timecard'
    | '/api/assoc-list'
    | '/api/assoc-manage'
    | '/children/$childId'
    | '/children'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/children'
    | '/dashboard'
    | '/diagnose'
    | '/main-book'
    | '/report'
    | '/timecard'
    | '/api/assoc-list'
    | '/api/assoc-manage'
    | '/children/$childId'
    | '/children/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  ChildrenRoute: typeof ChildrenRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DiagnoseRoute: typeof DiagnoseRoute
  MainBookRoute: typeof MainBookRoute
  ReportRoute: typeof ReportRoute
  TimecardRoute: typeof TimecardRoute
  ApiAssocListRoute: typeof ApiAssocListRoute
  ApiAssocManageRoute: typeof ApiAssocManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children': {
      id: '/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof ChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-book': {
      id: '/main-book'
      path: '/main-book'
      fullPath: '/main-book'
      preLoaderRoute: typeof MainBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timecard': {
      id: '/timecard'
      path: '/timecard'
      fullPath: '/timecard'
      preLoaderRoute: typeof TimecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assoc-list': {
      id: '/api/assoc-list'
      path: '/api/assoc-list'
      fullPath: '/api/assoc-list'
      preLoaderRoute: typeof ApiAssocListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assoc-manage': {
      id: '/api/assoc-manage'
      path: '/api/assoc-manage'
      fullPath: '/api/assoc-manage'
      preLoaderRoute: typeof ApiAssocManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children/': {
      id: '/children/'
      path: '/'
      fullPath: '/children/'
      preLoaderRoute: typeof ChildrenIndexRouteImport
      parentRoute: typeof ChildrenRoute
    }
    '/children/$childId': {
      id: '/children/$childId'
      path: '/$childId'
      fullPath: '/children/$childId'
      preLoaderRoute: typeof ChildrenChildIdRouteImport
      parentRoute: typeof ChildrenRoute
    }
  }
}

interface ChildrenRouteChildren {
  ChildrenChildIdRoute: typeof ChildrenChildIdRoute
  ChildrenIndexRoute: typeof ChildrenIndexRoute
}

const ChildrenRouteChildren: ChildrenRouteChildren = {
  ChildrenChildIdRoute: ChildrenChildIdRoute,
  ChildrenIndexRoute: ChildrenIndexRoute,
}

const ChildrenRouteWithChildren = ChildrenRoute._addFileChildren(
  ChildrenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  ChildrenRoute: ChildrenRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DiagnoseRoute: DiagnoseRoute,
  MainBookRoute: MainBookRoute,
  ReportRoute: ReportRoute,
  TimecardRoute: TimecardRoute,
  ApiAssocListRoute: ApiAssocListRoute,
  ApiAssocManageRoute: ApiAssocManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
